version: "3"
services:
  db:
    image: postgres:12.5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app: &app
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 3000:3000
volumes:
  pgdata:
