---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/orders/{order_id}/dispatches":
    post:
      summary: Create dispatch for order
      tags:
      - Dispatches
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Order dispatched and stock removed from the system.
        '422':
          description: Invalid record
        '404':
          description: Order not found
  "/orders":
    post:
      summary: Create Order
      tags:
      - Orders
      parameters: []
      responses:
        '201':
          description: Order created
        '404':
          description: Product or Warehouse not found
        '422':
          description: No stock available for the selected product and warehouse
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                warehouse_id:
                  type: integer
              required:
              - product_id
              - warehouse_id
  "/products":
    get:
      summary: List products
      tags:
      - Products
      responses:
        '200':
          description: Products listed
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    code:
                      type: string
                    description:
                      type: string
                  required:
                  - id
                  - code
                  - description
    post:
      summary: Create a new product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  code:
                    type: string
                  description:
                    type: string
                required:
                - id
                - code
                - description
        '422':
          description: Invalid request parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                description:
                  type: string
              required:
              - code
              - description
  "/products/{id}":
    get:
      summary: Get product details
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Product details found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  code:
                    type: string
                  description:
                    type: string
                required:
                - id
                - code
                - description
        '404':
          description: Product not found
    put:
      summary: Update product details
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Product details updated
        '404':
          description: Product not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                description:
                  type: string
              required:
              - code
              - description
    delete:
      summary: Delete a product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found
  "/stock_balances/{id}":
    get:
      summary: Get Stock Balance details
      tags:
      - Stock Balances
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Stock Balance details found
          content:
            application/json:
              schema:
                type: object
                properties:
                  stock_balance:
                    type: object
                    properties:
                      warehouse:
                        type: object
                        properties:
                          id:
                            type: integer
                          code:
                            type: string
                        required:
                        - id
                        - code
                      product:
                        type: object
                        properties:
                          id:
                            type: integer
                          code:
                            type: string
                          description:
                            type: string
                        required:
                        - id
                        - code
                        - description
                      available_stocks:
                        type: integer
                      ordered_stocks:
                        type: integer
                    required:
                    - warehouse
                    - product
                    - available_stocks
                    - ordered_stocks
                required:
                - stock_balance
        '404':
          description: Stock Balance not found
  "/stocks":
    get:
      summary: Retrieve all stocks
      tags:
      - Stocks
      responses:
        '200':
          description: Stocks retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    warehouse_id:
                      type: integer
                    product_id:
                      type: integer
                    quantity:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
    post:
      summary: Create a new stock
      tags:
      - Stocks
      parameters:
      - name: warehouse_id
        in: query
        schema:
          type: integer
      - name: product_id
        in: query
        schema:
          type: integer
      - name: quantity
        in: query
        schema:
          type: integer
      responses:
        '201':
          description: Stock created successfully
        '422':
          description: Invalid warehouse or product ID
  "/stocks/{id}":
    get:
      summary: Retrieve a stock
      tags:
      - Stocks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Stock retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  warehouse_id:
                    type: integer
                  product_id:
                    type: integer
                  quantity:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: Stock not found
  "/warehouses":
    get:
      summary: Retrieve all warehouses
      tags:
      - Warehouses
      responses:
        '200':
          description: Warehouses retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    code:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
    post:
      summary: Create a new warehouse
      tags:
      - Warehouses
      parameters: []
      responses:
        '201':
          description: Warehouse created successfully
        '422':
          description: Invalid request parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required:
              - code
  "/warehouses/{id}":
    get:
      summary: Retrieve a warehouse
      tags:
      - Warehouses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Warehouse retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  code:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: Warehouse not found
    put:
      summary: Update warehouse details
      tags:
      - Warehouses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Warehouse details updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required:
              - code
    delete:
      summary: Delete a warehouse
      tags:
      - Warehouses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Warehouse deleted
        '404':
          description: Warehouse not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
